FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    sqlite3

WORKDIR /app

COPY ./server /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py"]
