FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    sqlite3\
    libsqlite3-dev \
    gcc \
    build-essential\ 
    iputils-ping \
    iproute2 \ 
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./server /app

RUN pip install --no-cache-dir -r requirements.txt

# CMD ["sh", "-c", "python3 locator.py & python3 gestor.py & wait"]
# CMD ["python3","gestor.py"]

CMD ["sh", "-c", "/app/startup.sh & python3 gestor.py & wait"]