FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    vim \
    net-tools \
    sqlite3 \
    libsqlite3-dev \
    gcc \
    build-essential \
    iputils-ping \
    iproute2 \ 
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY ./client /app

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x ./startup.sh

CMD ["sh", "-c", "/app/startup.sh && tail -f /dev/null"]

